server:
  port: 9999
#  ssl:
#    enabled: true
#    client-auth: want
#    key-store: classpath:server.jks
#    key-store-password: eureka
#    trust-store: classpath:servertrust.jks
#    trust-store-password: eureka

spring:
  data:
    mongodb:
      username: weiliao
      host: 49.235.164.57
      port: 27017
      password: weiliao
      database: weiliao
fastdfs:
  tracker_servers: 49.235.164.57:22122
  connect_timeout_in_seconds: 60
  network_timeout_in_seconds: 600
  charset: UTF-8