server:
  port: 9999
    ssl:
      enabled: true
      client-auth: want
      key-store: classpath:server.jks
      key-store-password: eureka
      trust-store: classpath:servertrust.jks
      trust-store-password: eureka

spring:
  datasource:
    jdbcUrl: jdbc:mysql://106.13.18.96:3306/weiliao_user?characterEncoding=utf8
    driverClass: com.mysql.jdbc.Driver
    user: root
    password: mysql-root
  data:
    mongodb:
      username: weiliao
      host: 106.13.18.96
      port: 27017
      password: weiliao
      database: weiliao

wxconfig:
  appId: wxedfcddc996ccc43e
  appSecret: 9312ee4d79d6435cbcf67d19c13d8784