server:
  port: 8889
  servlet:
    session:
      timeout: 600000

#redis:
#  host: 192.168.12.53
#  port: 6379
#  password: ldvv

spring:
  data:
    mongodb:
      username: weiliao
      host: 106.13.18.96
      port: 27017
      password: weiliao
      database: weiliao
