server:
  port: 9999
  ssl:
    enabled: true
    client-auth: want
    key-store: classpath:server.jks
    key-store-password: eureka
    trust-store: classpath:servertrust.jks
    trust-store-password: eureka

spring:
  data:
    mongodb:
      username: weiliao
      host: 106.13.18.96
      port: 27017
      password: weiliao
      database: weiliao
